services:
  pipeline:

  minio:

  mlflow:

  tests:
      build:
        context: ./tests
        dockerfile: Dockerfile
      depends_on:
        - minio
        - mlflow
        - pipeline
      environment:
        - MINIO_ENDPOINT=minio:9000
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
        - MINIO_DATA_BUCKET=dvc-storage
        - MINIO_MLFLOW_BUCKET=mlflow-artifacts
        - MLFLOW_TRACKING_URI="http://mlflow:5000"